using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SaCompliance.Application.Interfaces;
using SaCompliance.Domain.Entities;

namespace SaCompliance.Infrastructure;

public class InvoicePdfGenerator : IInvoicePdfGenerator
{
    public byte[] GenerateInvoicePdf(Invoice invoice)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Text($"INVOICE {invoice.InvoiceNumber}")
                    .SemiBold().FontSize(20);

                page.Content().Column(column =>
                {
                    column.Spacing(10);

                    column.Item().Text($"Business ID: {invoice.BusinessId}");
                    column.Item().Text($"Invoice Date: {DateTime.UtcNow:yyyy-MM-dd}");

                    column.Item().LineHorizontal(1);

                    column.Item().Text($"Subtotal: R {invoice.SubTotal:F2}");
                    column.Item().Text($"VAT (15%): R {invoice.VatAmount:F2}");
                    column.Item().Text($"TOTAL: R {invoice.Total:F2}")
                        .Bold().FontSize(14);
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by SA Compliance Platform")
                    .FontSize(10)
                    .Italic();
            });
        });

        return document.GeneratePdf();
    }
}
